### ISSUE TITLE
[Feature Request] A  nodejs/web api

### ISSUE THREAD

**Issue by stoneRdev** [str1z/mlogcc#2]
First off, Killer work on this project!

I'd like to request a nodejs/web api for this project. My use case for this would be a website I can visit locally on my phone (while playing mobile version) with an editor, that can compile code for me to copy right from the website and back into mindustry.

If your ok with it, I can give a whack at a pull request for this feature, and maybe even provide you with the editor (once finished) that you could bundle into this project if you'd like

**Comment by stoneRdev** [comment]
Ha, I'm obviously blind, I just saw that module support is already here. I'm gonna get close this and get started on my web editor. Comment back here if you'd like me to provide the source when I'm done!

**Comment by str1z** [comment]
@stoneRdev, I was also thinking about doing a web version of it with an emulator included. If you need help with it, I will be happy to help you. We can be friends on discord if you want. wei#2893.

**Comment by stoneRdev** [comment]
@str1z Of course I'm down for a collab. I'll start us a repo for it. As for discord, I havent used it in ages so I'll have to revive all that

**Comment by stoneRdev** [comment]
@str1z Sent you a request on discord werlious#6136
